# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT8WkaYAohVrv1kwWBW7QhWQAoFOzoCp
"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import MobileNetV2
from google.colab import files
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# 1. LOAD A PRE-TRAINED MODEL (MobileNetV2)
# We use 'imagenet' weights as a starting point for general shape recognition
base_model = MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
base_model.trainable = False  # Freeze the model so we don't ruin the pre-trained weights

# 2. BUILD THE ARCHITECTURE
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(3, activation='softmax') # 3 Categories: Oily, Dry, Normal
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 3. DEFINE THE LABELS
labels = ['Dry', 'Normal', 'Oily']

print("Model is ready! Since we don't have a local dataset folder,")
print("let's simulate a prediction using an uploaded image.")

# 4. PREDICTION FUNCTION
def predict_skin():
    uploaded = files.upload()
    for fn in uploaded.keys():
        # Load and resize the image
        img_path = fn
        img = image.load_img(img_path, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) / 255.0 # Normalize

        # Make prediction
        prediction = model.predict(img_array)
        result = labels[np.argmax(prediction)]

        # Display Result
        plt.imshow(img)
        plt.title(f"Predicted Skin Type: {result}")
        plt.axis('off')
        plt.show()

        print(f"The AI thinks your skin type is: {result}")

# Run the uploader
predict_skin()
